### PR TITLE
chore: Bump vault_autounseal lib version

### PR DESCRIPTION
**Pull request by DanielArndt**
I forgot the version bump in #550 :disappointed: 

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ghislainbourgeois — COMMENTED** [review]
There's nothing here, should we close this?

**Comment by DanielArndt** [comment]
@ghislainbourgeois 

> There's nothing here, should we close this?

Mentioned in the description: I forgot the version bump in https://github.com/canonical/vault-k8s-operator/pull/550 😞

**Comment by ghislainbourgeois** [comment]
> @ghislainbourgeois
> 
> > There's nothing here, should we close this?
> 
> Mentioned in the description: I forgot the version bump in #550 😞

But I do not see a version bump in this one either, I see no changes at all.

**Comment by DanielArndt** [comment]
> > @ghislainbourgeois
> > > There's nothing here, should we close this?
> > 
> > 
> > Mentioned in the description: I forgot the version bump in #550 😞
> 
> But I do not see a version bump in this one either, I see no changes at all.

:laughing: it was bumped by another PR so there's no diff anymore. I guess you're right, it can be closed!

**Pull request closed without merging**
