### PR TITLE
[Feat] Uses clusterIP instead of LoadBalancer service

### PR DESCRIPTION
**Pull request by gruyaume**
# Description

Uses the default K8s service for charms (clusterIP) instead of a loadbalancer service. If LoadBalancer is required, this should be done by connecting to traffic instead.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ghislainbourgeois — APPROVED** [review]
Since this is a breaking change, should we have a new track to let people upgrade on their own terms?

**Comment by gruyaume** [comment]
> Since this is a breaking change, should we have a new track to let people upgrade on their own terms?

@ghislainbourgeois 
Right now this charm is only available on edge channel and doesn't support most of what we would consider production ready (HA + HTTPS).

In other words I'm not too worried about introducing breaking changes, at least not until we move to stable.

**Comment by ghislainbourgeois** [comment]
> > Since this is a breaking change, should we have a new track to let people upgrade on their own terms?
> 
> @ghislainbourgeois 
> Right now this charm is only available on edge channel and doesn't support most of what we would consider production ready (HA + HTTPS).
> 
> In other words I'm not too worried about introducing breaking changes, at least not until we move to stable.

Ok, that works for me.

**Comment by gboutry** [comment]
With this change, Vault won't be accessible from other nodes that don't have k8s networking defined, is that intended ?

**Pull request merged**
